services:
  - type: web
    name: playto-kyc-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py migrate && python seed.py"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-kyc-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      # Configs provided by user
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: shivakarnati69@gmail.com
      - key: SMTP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        value: shivakarnati69@gmail.com
      - key: OTP_EXPIRY_MINUTES
        value: "10"
      - key: OTP_LENGTH
        value: "6"
      - key: JWT_SECRET
        value: nutrivision_jwt_secret_2026_sk
      - key: DB_SSL
        value: "false"

  - type: web
    name: playto-kyc-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: playto-kyc-backend
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: playto-kyc-db
    databaseName: playto
    user: postgres
