# Generated by Django 4.2.13 on 2026-04-26 02:40

import apps.kyc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, choices=[('individual', 'Individual / Freelancer'), ('sole_proprietor', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('llp', 'LLP'), ('other', 'Other')], max_length=30)),
                ('monthly_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_requested', 'More Info Requested')], db_index=True, default='draft', max_length=30)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('bank_statement', 'Bank Statement')], max_length=20)),
                ('file', models.FileField(upload_to=apps.kyc.models._document_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycsubmission')),
            ],
            options={
                'unique_together': {('submission', 'doc_type')},
            },
        ),
    ]
